import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AddMedicationFlow } from '@/components/add-medication-flow';
import { TodayDose, useMedications } from '@/context/medications';

export default function TodayScreen() {
  const { todayDoses, ready, takeDose, skipDose } = useMedications();
  const [showAddFlow, setShowAddFlow] = useState(false);
  function confirmSkip(dose: TodayDose) { Alert.alert('Пропустить приём?', `${dose.medicationName} останется в истории как пропущенный. Остаток в аптечке не изменится.`, [{ text: 'Отмена', style: 'cancel' }, { text: 'Пропустить', style: 'destructive', onPress: () => void skipDose(dose.id) }]); }
  return <View style={styles.screen}><SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>СЕГОДНЯ</Text><Text style={styles.title}>Приёмы</Text></View><Pressable accessibilityLabel="Добавить лекарство" onPress={() => setShowAddFlow(true)} style={({ pressed }) => [styles.addButton, pressed && styles.pressedCompact]}><Text style={styles.addButtonText}>＋</Text></Pressable></View>
    {!ready ? <View style={styles.loader}><ActivityIndicator color="#1688F7" /></View> : todayDoses.length === 0 ? <EmptyState onAdd={() => setShowAddFlow(true)} /> : <View style={styles.schedule}><Text style={styles.sectionTitle}>На сегодня</Text><View style={styles.list}>{todayDoses.map((dose) => <DoseRow key={dose.id} dose={dose} onTake={() => void takeDose(dose.id)} onSkip={() => confirmSkip(dose)} />)}</View></View>}
  </ScrollView><AddMedicationFlow visible={showAddFlow} onClose={() => setShowAddFlow(false)} /></SafeAreaView></View>;
}

function EmptyState({ onAdd }: { onAdd: () => void }) { return <View style={styles.empty}><View style={styles.emptyIcon}><Text style={styles.emptyIconText}>＋</Text></View><Text style={styles.emptyTitle}>Сегодня нет приёмов</Text><Text style={styles.emptyDescription}>Добавь препарат в аптечку и настрой схему, когда будешь готов.</Text><Pressable onPress={onAdd} style={({ pressed }) => [styles.primaryButton, pressed && styles.pressed]}><Text style={styles.primaryButtonText}>Добавить препарат</Text></Pressable></View>; }
function DoseRow({ dose, onTake, onSkip }: { dose: TodayDose; onTake: () => void; onSkip: () => void }) {
  const completed = dose.status !== 'pending';
  return <View style={styles.row}><View style={[styles.colorMark, { backgroundColor: dose.color }]} /><View style={styles.info}><Text style={styles.time}>{dose.time}</Text><Text style={styles.name}>{dose.medicationName}</Text><Text style={styles.details}>{dose.quantity} {dose.stockUnit} · {dose.form} {dose.amount} {dose.unit}</Text>{completed ? <Text style={[styles.completed, dose.status === 'taken' ? styles.taken : styles.skipped]}>{dose.status === 'taken' ? 'Принято' : 'Пропущено'}</Text> : <View style={styles.actions}><Pressable onPress={onTake} style={({ pressed }) => [styles.takeButton, pressed && styles.pressed]}><Text style={styles.takeText}>Принять</Text></Pressable><Pressable onPress={onSkip} style={({ pressed }) => [styles.skipButton, pressed && styles.pressed]}><Text style={styles.skipText}>Пропустить</Text></Pressable></View>}</View></View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F8FA' }, safeArea: { flex: 1 }, content: { padding: 20, paddingBottom: 116, flexGrow: 1 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 }, eyebrow: { color: '#747A85', fontSize: 12, fontWeight: '700', letterSpacing: 0.8 }, title: { color: '#15171B', fontSize: 36, fontWeight: '700', letterSpacing: -1.1, marginTop: 2 }, addButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#17191D', alignItems: 'center', justifyContent: 'center' }, addButtonText: { color: '#FFFFFF', fontSize: 27, fontWeight: '300', marginTop: -2 }, loader: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingTop: 150 }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28, paddingTop: 100 }, emptyIcon: { height: 88, width: 88, borderRadius: 44, backgroundColor: '#DFF2FF', alignItems: 'center', justifyContent: 'center' }, emptyIconText: { color: '#1688F7', fontSize: 45, fontWeight: '300', marginTop: -4 }, emptyTitle: { color: '#17191E', fontSize: 25, fontWeight: '700', marginTop: 24, textAlign: 'center' }, emptyDescription: { color: '#727986', fontSize: 16, lineHeight: 23, textAlign: 'center', marginTop: 10 }, primaryButton: { backgroundColor: '#1688F7', borderRadius: 20, minHeight: 58, paddingHorizontal: 25, alignItems: 'center', justifyContent: 'center', marginTop: 28 }, primaryButtonText: { color: '#FFFFFF', fontSize: 17, fontWeight: '700' }, schedule: { marginTop: 34 }, sectionTitle: { color: '#20232A', fontSize: 20, fontWeight: '700', marginBottom: 12 }, list: { backgroundColor: '#FFFFFF', borderRadius: 24, overflow: 'hidden' }, row: { minHeight: 118, padding: 17, flexDirection: 'row', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E8EAF0' }, colorMark: { width: 8, borderRadius: 4, marginRight: 13, marginVertical: 3 }, info: { flex: 1 }, time: { color: '#6E7480', fontSize: 13, fontWeight: '600' }, name: { color: '#1C1F25', fontSize: 17, fontWeight: '700', marginTop: 2 }, details: { color: '#737A85', fontSize: 13, marginTop: 2 }, actions: { flexDirection: 'row', gap: 9, marginTop: 13 }, takeButton: { backgroundColor: '#1688F7', paddingVertical: 8, paddingHorizontal: 13, borderRadius: 12 }, takeText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 }, skipButton: { backgroundColor: '#F1F2F5', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 12 }, skipText: { color: '#5F6672', fontWeight: '700', fontSize: 13 }, completed: { fontSize: 13, fontWeight: '700', marginTop: 12 }, taken: { color: '#239B72' }, skipped: { color: '#AA6271' }, pressed: { opacity: 0.74, transform: [{ scale: 0.985 }] }, pressedCompact: { opacity: 0.58, transform: [{ scale: 0.94 }] },
});
