import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { Medication, StockUnit, stockUnitFor } from '@/context/medications';

type Props = { medication: Medication | null; remainingStock: number; onClose: () => void };

export function MedicationDetailsSheet({ medication, remainingStock, onClose }: Props) {
  if (!medication) return null;
  const unit: StockUnit = stockUnitFor(medication.form);
  const schedule = medication.schedules.length ? medication.schedules.map((item) => `${item.time} · ${item.doseQuantity} ${item.doseUnit}`).join(', ') : 'По необходимости';
  return <Modal visible animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><View style={styles.screen}><View style={styles.header}><Text style={styles.title}>Карточка препарата</Text><Pressable onPress={onClose} style={({ pressed }) => [styles.close, pressed && styles.pressed]}><Text style={styles.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}><View style={[styles.icon, { backgroundColor: medication.color }]}><Text style={styles.iconText}>{medication.form === 'Жидкость' || medication.form === 'Капли' || medication.form === 'Сироп' ? '◒' : medication.form === 'Капсула' ? '●' : '◉'}</Text></View><Text style={styles.name}>{medication.name}</Text><Text style={styles.subtitle}>{medication.form} · {medication.amount} {medication.unit}</Text><Section title="Приём"><Text style={styles.value}>{schedule}</Text></Section><Section title="В аптечке"><Text style={styles.stock}>{remainingStock} {unit} в наличии</Text>{medication.packages.map((pack, index) => <View key={pack.id} style={styles.package}><Text style={styles.packageTitle}>Упаковка {index + 1}</Text><Text style={styles.packageText}>Осталось {pack.remainingQuantity} {pack.unit}{pack.expiresOn ? ` · годен до ${pack.expiresOn}` : ' · срок не указан'}</Text></View>)}</Section>{medication.barcode ? <Section title="Штрихкод"><Text style={styles.value}>{medication.barcode}</Text></Section> : null}</ScrollView></View></Modal>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.sectionCard}>{children}</View></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7F8FA' }, header: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { fontSize: 17, fontWeight: '700', color: '#17191E' }, close: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#ECEEF1', alignItems: 'center', justifyContent: 'center' }, closeText: { fontSize: 29, fontWeight: '300', lineHeight: 32, color: '#17191E' }, content: { padding: 24, paddingBottom: 50 }, icon: { width: 86, height: 86, borderRadius: 43, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginTop: 8 }, iconText: { color: '#FFF', fontSize: 42 }, name: { color: '#17191E', fontSize: 30, letterSpacing: -0.8, fontWeight: '700', textAlign: 'center', marginTop: 22 }, subtitle: { color: '#707784', fontSize: 17, textAlign: 'center', marginTop: 5 }, section: { marginTop: 30 }, sectionTitle: { color: '#20232A', fontSize: 18, fontWeight: '700', marginBottom: 10 }, sectionCard: { backgroundColor: '#FFF', borderRadius: 20, padding: 17 }, value: { color: '#343A44', fontSize: 16, lineHeight: 22 }, stock: { color: '#25805F', fontSize: 17, fontWeight: '700' }, package: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#E7EAF0', paddingTop: 13, marginTop: 13 }, packageTitle: { color: '#313640', fontSize: 15, fontWeight: '700' }, packageText: { color: '#727A86', fontSize: 14, lineHeight: 20, marginTop: 4 }, pressed: { opacity: 0.65, transform: [{ scale: 0.96 }] } });
