import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { Medication, StockUnit, stockUnitFor } from '@/context/medications';

type Props = { medication: Medication | null; remainingStock: number; onClose: () => void; onDelete: (medicationId: string) => void };

export function MedicationDetailsSheet({ medication, remainingStock, onClose, onDelete }: Props) {
  if (!medication) return null;
  const currentMedication = medication;
  const unit: StockUnit = stockUnitFor(medication.form);
  const schedule = medication.schedules.length ? medication.schedules.map((item) => `${item.time} · ${item.doseQuantity} ${item.doseUnit}`).join(', ') : 'По необходимости';
  function confirmDelete() { Alert.alert('Удалить препарат?', `Будут удалены «${currentMedication.name}», его упаковки, история и будущие напоминания. Это действие нельзя отменить.`, [{ text: 'Отмена', style: 'cancel' }, { text: 'Удалить', style: 'destructive', onPress: () => onDelete(currentMedication.id) }]); }
  return <Modal visible animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><View style={styles.screen}><View style={styles.header}><Text style={styles.title}>Карточка препарата</Text><Pressable onPress={onClose} style={({ pressed }) => [styles.close, pressed && styles.pressed]}><Text style={styles.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}><View style={[styles.icon, { backgroundColor: medication.color }]}><Text style={styles.iconText}>{medication.form === 'Жидкость' || medication.form === 'Капли' || medication.form === 'Сироп' ? '◒' : medication.form === 'Капсула' ? '●' : '◉'}</Text></View><Text style={styles.name}>{medication.name}</Text><Text style={styles.subtitle}>{medication.form} · {medication.amount} {medication.unit}</Text><Section title="Приём"><Text style={styles.value}>{schedule}</Text></Section><Section title="В аптечке"><Text style={styles.stock}>{remainingStock} {unit} доступно для приёма</Text>{medication.packages.map((pack, index) => <PackageRow key={pack.id} index={index} pack={pack} />)}</Section>{medication.barcode ? <Section title="Штрихкод"><Text style={styles.value}>{medication.barcode}</Text></Section> : null}<Pressable onPress={confirmDelete} style={({ pressed }) => [styles.deleteButton, pressed && styles.pressed]}><Text style={styles.deleteText}>Удалить препарат</Text></Pressable></ScrollView></View></Modal>;
}

function PackageRow({ pack, index }: { pack: Medication['packages'][number]; index: number }) {
  const today = new Date(); const todayKey = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
  const expired = Boolean(pack.expiresOn && pack.expiresOn < todayKey);
  return <View style={styles.package}><Text style={styles.packageTitle}>Упаковка {index + 1}</Text><Text style={[styles.packageText, expired && styles.packageExpired]}>Осталось {pack.remainingQuantity} {pack.unit}{pack.expiresOn ? ` · годен до ${formatDate(pack.expiresOn)}` : ' · срок не указан'}{expired ? ' · просрочена и не списывается' : ''}</Text></View>;
}

function formatDate(value: string) { return /^\d{4}-\d{2}-\d{2}$/.test(value) ? `${value.slice(8, 10)}.${value.slice(5, 7)}.${value.slice(0, 4)}` : value; }

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.sectionCard}>{children}</View></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7F8FA' }, header: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { fontSize: 17, fontWeight: '700', color: '#17191E' }, close: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#ECEEF1', alignItems: 'center', justifyContent: 'center' }, closeText: { fontSize: 29, fontWeight: '300', lineHeight: 32, color: '#17191E' }, content: { padding: 24, paddingBottom: 50 }, icon: { width: 86, height: 86, borderRadius: 43, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginTop: 8 }, iconText: { color: '#FFF', fontSize: 42 }, name: { color: '#17191E', fontSize: 30, letterSpacing: -0.8, fontWeight: '700', textAlign: 'center', marginTop: 22 }, subtitle: { color: '#707784', fontSize: 17, textAlign: 'center', marginTop: 5 }, section: { marginTop: 30 }, sectionTitle: { color: '#20232A', fontSize: 18, fontWeight: '700', marginBottom: 10 }, sectionCard: { backgroundColor: '#FFF', borderRadius: 20, padding: 17 }, value: { color: '#343A44', fontSize: 16, lineHeight: 22 }, stock: { color: '#25805F', fontSize: 17, fontWeight: '700' }, package: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#E7EAF0', paddingTop: 13, marginTop: 13 }, packageTitle: { color: '#313640', fontSize: 15, fontWeight: '700' }, packageText: { color: '#727A86', fontSize: 14, lineHeight: 20, marginTop: 4 }, packageExpired: { color: '#B45A5A' }, deleteButton: { marginTop: 34, minHeight: 54, borderRadius: 17, backgroundColor: '#FCEDEF', alignItems: 'center', justifyContent: 'center' }, deleteText: { color: '#B52E3C', fontSize: 16, fontWeight: '700' }, pressed: { opacity: 0.65, transform: [{ scale: 0.96 }] } });
